version: "3.6"

services:
  mongo:
    image: mongo:4
    container_name: url-mongo
    restart: "no"
    volumes:
      - ./docker/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: url-mongo-express
    restart: "no"
    ports:
      - 27020:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
